#XXX: the strings are not format strings because the evaluation would happen
#XXX: before ip, user and pass are defined; making invalid URLs
urls = {

    "axis": [
        'http://{ip}/mjpg/video.mjpg',
        'rtsp://{ip}/mpeg4/media.amp ',
        'rtsp://{ip}/axis-media/media.amp?',
        'rtsp://{ip}/onvif-media/media.amp',
        'http://{ip}/axis-cgi/mjpg/video.cgi',
        'rtsp://{ip}/ucast/12',
        'http://{ip}/mjpg/1/video.mjpg?Axis-Orig-Sw=true',
        'http://{ip}/stream.asf',
        'http://{ip}/mjpg/1/video.mjpg',
        'rtsp://{ip}/mpeg4',
    ],

    "sony": [
        'rtsp://{ip}/media/video1',
        'http://{ip}/h264',
        'rtsp://{ip}/av0_0',
        'rtsp://{ip}/live1.264',
        'rtsp://{ip}/mjpeg',
        'rtsp://{ip}/video1',
        'rtsp://{ip}/11',
        'rtsp://{ip}/videoinput_1:0/h264_1/onvif.stm',
        'http://{ip}/oneshotimage1?COUNTER',
        'rtsp://{ip}/profile',
        'rtsp://{ip}/stream.asf',
        'rtsp://{ip}/live/mpeg4',
    ],

    "bosch": [
        'rtsp://{ip}/h26x=4&inst=2',
        'rtsp://{ip}/h26x=4&inst=1',
        'rtsp://{ip}/rtsp_tunnel',
        'rtsp://{ip}/video.h264',
        'rtsp://{ip}/11',
        'rtsp://{ip}/h264',
        'rtsp://{ip}/1/stream1/Profile1',
        'rtsp://{ip}/ch1-s1',
        'rtsp://{ip}/line=2',
    ],

    "hikvision": [
        'rtsp://{ip}/MediaInput/h264',
        'rtsp://{ip}/Streaming/Channels/1',
        'rtsp://{ip}/Streaming/Channels/101',
        'rtsp://{ip}/video.h264',
        'rtsp://{ip}/HighResolutionVideo',
        'rtsp://{ip}/mpeg4',
        'rtsp://{ip}/H264',
        'rtsp://{ip}/Streaming/Channels/102',
        'rtsp://{ip}/Streaming/Channels/201',
        'rtsp://{ip}/Streaming/Channels/301',
        'rtsp://{ip}/Streaming/Channels/401',
        'rtsp://{ip}/Streaming/Channels/501',
        'rtsp://{ip}/h264/ch01/main/av_stream',
        'rtsp://{ip}/cam1/mpeg4',
        'rtsp://{ip}/mpeg4/media.amp?',
        'rtsp://{ip}/ch0_0.h264',
        'rtsp://{ip}/cam1/onvif-h264',
        'rtsp://{ip}/11',
        'rtsp://{ip}/live',
        'rtsp://{ip}//Streaming/Channels/2',
        'rtsp://{ip}/h264',
        'rtsp://{ip}/rtsph2641080p',
        'rtsp://{ip}/live.sdp',
        'rtsp://{ip}/videoMain',
        'rtsp://{ip}/Streaming/Channels/103',
        'rtsp://{ip}/PSIA/Streaming/channels/0',
        'rtsp://{ip}/LowResolutionVideo',
        'rtsp://{ip}/cam1/onvif-h264-1',
        'rtsp://{ip}/ch0_0.h264',
        'rtsp://{ip}/1',
        'rtsp://{ip}/image.mpg',
        'rtsp://{ip}/live.sdp',
        'rtsp://{ip}/h264_stream',
        'rtsp://{ip}/live/ch0',
        'rtsp://{ip}/live/ch00_0',
        'rtsp://{ip}/cam0/h264',
        'rtsp://{ip}/live/h264',
        'rtsp://{ip}/live/av0',
        'rtsp://{ip}/',
        'rtsp://{ip}/av0_1',
        'rtsp://{ip}/Video',
        'rtsp://{ip}/mpeg4',
        'rtsp://{ip}/onvif/live/2',
        'rtsp://{ip}/cam/realmonitor',
        'rtsp://{ip}/ucast/11',
        'rtsp://{ip}/main',
        'rtsp://{ip}/0',
        'rtsp://{ip}/Streaming/Unicast/channels/101',
        'rtsp://{ip}/ISAPI/streaming/channels/102',
        'rtsp://{ip}/ISAPI/streaming/channels/101',
    ],

    "avigilon": [
        'rtsp://{ip}/deaultPrimary0streamtype=u',
        'http://{ip}/media/still.jpg',
    ],

    "panasonic": [
        'http://{ip}/SnapshotJPEG?Resolution=640x480&amp;Quality=Clarity',
        'rtsp://{ip}/ONVIF/MediaInput',
        'http://{ip}/videostream.asf?user={usr}&pwd={pwd}',
        'rtsp://{ip}/cam/realmonitor',
        'rtsp://{ip}/live.sdp',
        'http://{ip}/videostream.asf',
        'rtsp://{ip}/MediaInput/h264',
        'rtsp://{ip}/MediaInput/mpeg4',
    ],

    "mobotix": [
        'http://{ip}/cgi-bin/faststream.jpg?stream=half&fps=15&rand=COUNTER',
        'rtsp://{ip}/control/faststream.jpg?stream=MxPEG&needlength&fps=6',
        'rtsp://{ip}/control/faststream.jpg?stream=full',
        'rtsp://{ip}/onvif/stream3/mobotix.mjpeg',
        'rtsp://{ip}/onvif/mobotix.h264',
        'rtsp://{ip}/streams/view/0',
    ],

    "cohu": [
        'rtsp://{ip}/ucast/11',
        'rtsp://{ip}/11',
        'rtsp://{ip}/stream1',
        'rtsp://{ip}/1',
    ],

    "wti": [
        'rtsp://{ip}/swVideo',
    ],

    "iqeye": [
        'rtsp://{ip}/rtsp/onvif',
        'rtsp://{ip}/rtsp/stream1',
        'rtsp://{ip}/stream1',
        'rtsp://{ip}/rtsp/now.mp4',
        'rtsp://{ip}/rtsp/now.jpg',
    ],

    "pelco": [
        'rtsp://{ip}/stream1',
        'rtsp://{ip}/1/stream1',
        'http://{ip}/jpeg',
    ],

    "flir": [
        'rtsp://{ip}/axis-cgi/mjpg/video.cgi',
        'rtsp://{ip}/cam/realmonitor',
        'rtsp://{ip}/ch0',
        'rtsp://{ip}/vis',
        'rtsp://{ip}/wfov',
    ],

    "univision": [
        'rtsp://{ip}/media/video1',
        'rtsp://{ip}/live3.sdp',
        'rtsp://{ip}/Streaming/Channels/1',
        'rtsp://{ip}/Streaming/Channels/2',
    ],

    "vicon": [
        'rtsp://{ip}/h264',
    ],

    "geovision": [
        'rtsp://{ip}/CH001.sdp',
        'rtsp://{ip}/CH002.sdp',
        'rtsp://{ip}/Streaming/Channels/1',
        'rtsp://{ip}/media/video1',
        'rtsp://{ip}/0/{usr}:{pwd}/main',
        'rtsp://{ip}/h264_stream',
        'rtsp://{ip}/videostream.asf?',
        'http://{ip}/cgi-bin/jpg/image.cgi',
        'http://{ip}/img/snapshot.cgi?size=2',
    ],
}

urls_auth = {
    "axis": [
        'http://{usr}:{pwd}@{ip}/mjpg/video.mjpg',
        'rtsp://{usr}:{pwd}@{ip}/mpeg4/media.amp',
        'rtsp://{usr}:{pwd}@{ip}/axis-media/media.amp?',
        'rtsp://{usr}:{pwd}@{ip}/onvif-media/media.amp',
        'http://{usr}:{pwd}@{ip}/axis-cgi/mjpg/video.cgi',
        'rtsp://{usr}:{pwd}@{ip}/ucast/12',
        'http://{ip}/videostream.asf?user={usr}&pwd={pwd}&resolution=64&rate=0',
        'http://{ip}/videostream.asf?user={usr}&pwd={pwd}',
        'http://{ip}/videostream.asf?usr={usr}&pwd={pwd}',
        'http://{usr}:{pwd}@{ip}/mjpg/1/video.mjpg?Axis-Orig-Sw=true',
        'http://{usr}:{pwd}@{ip}/stream.asf',
        'http://{usr}:{pwd}@{ip}/mjpg/1/video.mjpg',
        'rtsp://{usr}:{pwd}@{ip}/mpeg4',
    ],

    "sony": [
        'rtsp://{usr}:{pwd}@{ip}/media/video1',
        'http://{usr}:{pwd}@{ip}/h264',
        'rtsp://{usr}:{pwd}@{ip}/av0_0',
        'rtsp://{usr}:{pwd}@{ip}/live1.264',
        'rtsp://{usr}:{pwd}@{ip}/mjpeg',
        'rtsp://{usr}:{pwd}@{ip}/video1',
        'rtsp://{usr}:{pwd}@{ip}/11',
        'rtsp://{ip}/user={usr}_password={pwd}_channel=1_stream=0.sdp',
        'http://{ip}/videostream.asf?usr={usr}&pwd={pwd}',
        'rtsp://{usr}:{pwd}@{ip}/videoinput_1:0/h264_1/onvif.stm',
        'http://{usr}:{pwd}@{ip}/oneshotimage1?COUNTER',
        'rtsp://{usr}:{pwd}@{ip}/profile',
        'rtsp://{usr}:{pwd}@{ip}/stream.asf',
        'rtsp://{usr}:{pwd}@{ip}/live/mpeg4',
    ],

    "bosch": [
        'rtsp://{usr}:{pwd}@{ip}/h26x=4&inst=2',
        'rtsp://{usr}:{pwd}@{ip}/h26x=4&inst=1',
        'rtsp://{usr}:{pwd}@{ip}/rtsp_tunnel',
        'rtsp://{usr}:{pwd}@{ip}/video.h264',
        'rtsp://{usr}:{pwd}@{ip}/11',
        'rtsp://{usr}:{pwd}@{ip}/h264',
        'rtsp://{usr}:{pwd}@{ip}/1/stream1/Profile1',
        'rtsp://{usr}:{pwd}@{ip}/ch1-s1',
        'rtsp://{usr}:{pwd}@{ip}/line=2',
    ],

    "hikvision": [
        'rtsp://{usr}:{pwd}@{ip}/MediaInput/h264',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/1',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/101',
        'rtsp://{usr}:{pwd}@{ip}/video.h264',
        'rtsp://{usr}:{pwd}@{ip}/HighResolutionVideo',
        'rtsp://{usr}:{pwd}@{ip}/mpeg4',
        'rtsp://{usr}:{pwd}@{ip}/H264',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/102',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/201',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/301',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/401',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/501',
        'rtsp://{usr}:{pwd}@{ip}/h264/ch01/main/av_stream',
        'rtsp://{usr}:{pwd}@{ip}/cam1/mpeg4',
        'rtsp://{usr}:{pwd}@{ip}/mpeg4/media.amp?',
        'rtsp://{usr}:{pwd}@{ip}/ch0_0.h264',
        'rtsp://{usr}:{pwd}@{ip}/cam1/onvif-h264',
        'rtsp://{usr}:{pwd}@{ip}/11',
        'rtsp://{usr}:{pwd}@{ip}/live',
        'rtsp://{usr}:{pwd}@{ip}//Streaming/Channels/2',
        'rtsp://{usr}:{pwd}@{ip}/h264',
        'rtsp://{usr}:{pwd}@{ip}/rtsph2641080p',
        'rtsp://{usr}:{pwd}@{ip}/live.sdp',
        'rtsp://{usr}:{pwd}@{ip}/videoMain',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/103',
        'rtsp://{usr}:{pwd}@{ip}/PSIA/Streaming/channels/0',
        'rtsp://{usr}:{pwd}@{ip}/LowResolutionVideo',
        'rtsp://{usr}:{pwd}@{ip}/cam1/onvif-h264-1',
        'rtsp://{usr}:{pwd}@{ip}/ch0_0.h264',
        'rtsp://{usr}:{pwd}@{ip}/1',
        'rtsp://{usr}:{pwd}@{ip}/image.mpg',
        'rtsp://{usr}:{pwd}@{ip}/live.sdp',
        'rtsp://{usr}:{pwd}@{ip}/h264_stream',
        'rtsp://{usr}:{pwd}@{ip}/live/ch0',
        'rtsp://{usr}:{pwd}@{ip}/live/ch00_0',
        'rtsp://{usr}:{pwd}@{ip}/cam0/h264',
        'rtsp://{usr}:{pwd}@{ip}/live/h264',
        'rtsp://{usr}:{pwd}@{ip}/live/av0',
        'rtsp://{ip}/user={usr}_password={pwd}_channel=1_stream=1.sdp',
        'rtsp://{usr}:{pwd}@{ip}/',
        'rtsp://{ip}/videostream.asf?user={usr}&pwd={pwd}&resolution=64&rate=0',
        'rtsp://{usr}:{pwd}@{ip}/av0_1',
        'rtsp://{usr}:{pwd}@{ip}/Video',
        'rtsp://{usr}:{pwd}@{ip}/mpeg4',
        'rtsp://{usr}:{pwd}@{ip}/onvif/live/2',
        'rtsp://{usr}:{pwd}@{ip}/cam/realmonitor',
        'rtsp://{usr}:{pwd}@{ip}/ucast/11',
        'rtsp://{usr}:{pwd}@{ip}/main',
        'rtsp://{usr}:{pwd}@{ip}/0',
        'rtsp://{ip}/user={usr}_password={pwd}_channel=1_stream=0.sdp',
        'rtsp://{ip}/user={usr}&password={pwd}&channel=1&stream=0.sdp',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Unicast/channels/101',
        'rtsp://{usr}:{pwd}@{ip}/ISAPI/streaming/channels/102',
        'rtsp://{usr}:{pwd}@{ip}/ISAPI/streaming/channels/101',
    ],

    "avigilon": [
        'rtsp://{usr}:{pwd}@{ip}/deaultPrimary0streamtype=u',
        'http://{usr}:{pwd}@{ip}/media/still.jpg',
    ],

    "panasonic": [
        'http://{usr}:{pwd}@{ip}/SnapshotJPEG?Resolution=640x480&amp;Quality=Clarity',
        'rtsp://{usr}:{pwd}@{ip}/ONVIF/MediaInput',
        'http://{ip}/videostream.asf?user={usr}&pwd={pwd}',
        'rtsp://{usr}:{pwd}@{ip}/cam/realmonitor',
        'rtsp://{usr}:{pwd}@{ip}/live.sdp',
        'http://{ip}/videostream.asf',
        'rtsp://{usr}:{pwd}@{ip}/MediaInput/h264',
        'rtsp://{usr}:{pwd}@{ip}/MediaInput/mpeg4',
    ],

    "mobotix": [
        'http://{usr}:{pwd}@{ip}/cgi-bin/faststream.jpg?stream=half&fps=15&rand=COUNTER',
        'rtsp://{usr}:{pwd}@{ip}/control/faststream.jpg?stream=MxPEG&needlength&fps=6',
        'rtsp://{usr}:{pwd}@{ip}/control/faststream.jpg?stream=full',
        'rtsp://{usr}:{pwd}@{ip}/onvif/stream3/mobotix.mjpeg',
        'rtsp://{usr}:{pwd}@{ip}/onvif/mobotix.h264',
        'rtsp://{usr}:{pwd}@{ip}/streams/view/0',
    ],

    "cohu": [
        'rtsp://{usr}:{pwd}@{ip}/ucast/11',
        'rtsp://{usr}:{pwd}@{ip}/11',
        'rtsp://{usr}:{pwd}@{ip}/stream1',
        'rtsp://{usr}:{pwd}@{ip}/1',
    ],

    "wti": [
        'rtsp://{usr}:{pwd}@{ip}/swVideo',
    ],

    "iqeye": [
        'rtsp://{usr}:{pwd}@{ip}/rtsp/onvif',
        'rtsp://{usr}:{pwd}@{ip}/rtsp/stream1',
        'rtsp://{usr}:{pwd}@{ip}/stream1',
        'rtsp://{usr}:{pwd}@{ip}/rtsp/now.mp4',
        'rtsp://{usr}:{pwd}@{ip}/rtsp/now.jpg',
    ],

    "pelco": [
        'rtsp://{usr}:{pwd}@{ip}/stream1',
        'rtsp://{usr}:{pwd}@{ip}/1/stream1',
        'http://{usr}:{pwd}@{ip}/jpeg',
    ],

    "flir": [
        'rtsp://{usr}:{pwd}@{ip}/axis-cgi/mjpg/video.cgi',
        'rtsp://{usr}:{pwd}@{ip}/cam/realmonitor',
        'rtsp://{usr}:{pwd}@{ip}/ch0',
        'rtsp://{usr}:{pwd}@{ip}/vis',
        'rtsp://{usr}:{pwd}@{ip}/wfov',
    ],

    "univision": [
        'rtsp://{usr}:{pwd}@{ip}/media/video1',
        'rtsp://{usr}:{pwd}@{ip}/live3.sdp',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/1',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/2',
    ],

    "vicon": [
        'rtsp://{usr}:{pwd}@{ip}/h264',
    ],

    "geovision": [
        'rtsp://{usr}:{pwd}@{ip}/CH001.sdp',
        'rtsp://{usr}:{pwd}@{ip}/CH002.sdp',
        'rtsp://{usr}:{pwd}@{ip}/Streaming/Channels/1',
        'rtsp://{usr}:{pwd}@{ip}/media/video1',
        'rtsp://{ip}/0/{usr}:{pwd}/main',
        'rtsp://{usr}:{pwd}@{ip}/h264_stream',
        'rtsp://{usr}:{pwd}@{ip}/videostream.asf?',
        'htpp://{usr}:{pwd}@{ip}/cgi-bin/jpg/image.cgi',
        'http://{usr}:{pwd}@{ip}/img/snapshot.cgi?size=2',
    ],
}
